name: "Get the AWS ECR image"
description: "Get the docker image on AWS ECR. Return 1 if exists, 0 otherwise"
inputs:
  aws-access-key-id:
    required: true
  aws-secret-access-key:
    required: true
  aws-region:
    required: true
  aws-ecr-repo-name:
    required: true
  aws-ecr-tag:
    required: true

outputs:
  aws-ecr-image-exist:
    description: "The variable to store the result for docker image checking"
    value: ${{ steps.ecr-image.outputs.image-exist }}

runs:
  using: "composite"
  steps:
    - uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region }}
    - id: ecr-image
      shell: bash
      run: |
        if aws ecr describe-images --repository-name  ${{ inputs.aws-ecr-repo-name }} --image-ids imageTag=${{ inputs.aws-ecr-tag }} > /dev/null 2>&1; then
          echo "image-exist=1" >> $GITHUB_OUTPUT
        else
          echo "image-exist=0" >> $GITHUB_OUTPUT
        fi
